// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izvnxadirljxkegreucy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dm54YWRpcmxqeGtlZ3JldWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDM5MzcsImV4cCI6MjA3MzYxOTkzN30.fWgBWy1d2Zv7dnkRuvnvXT84dtuymYn7rjGaQG4UBs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});